# Generated by Django 5.2.7 on 2025-10-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='model_info',
            field=models.TextField(blank=True, help_text='Detailed information about the model'),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='model_file',
            field=models.CharField(help_text='Path to the main model file', max_length=200),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='scaler_file',
            field=models.CharField(blank=True, help_text='Path to the scaler file', max_length=200, null=True),
        ),
    ]
