# Generated by Django 5.2.3 on 2025-10-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_problemstatement_model_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='approach_explanation',
            field=models.TextField(blank=True, help_text='Our approach and model selection reasoning', null=True),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='model_architecture',
            field=models.TextField(blank=True, help_text='Model architecture, parameters, and hyperparameters', null=True),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='preprocessing_steps',
            field=models.TextField(blank=True, help_text='Data preprocessing and feature engineering techniques', null=True),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='problem_statement_detail',
            field=models.TextField(blank=True, help_text='Detailed problem explanation for beginners', null=True),
        ),
    ]
