# Generated by Django 5.2.3 on 2025-10-29 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_problemstatement_approach_explanation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin feedback or notes')),
                ('title', models.CharField(help_text='Title of your ML project', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the problem and solution')),
                ('model_type', models.CharField(choices=[('Classification', 'Classification'), ('Regression', 'Regression'), ('Clustering', 'Clustering'), ('Deep Learning', 'Deep Learning'), ('NLP', 'Natural Language Processing'), ('Computer Vision', 'Computer Vision'), ('Other', 'Other')], default='Classification', max_length=100)),
                ('model_file', models.FileField(help_text='Upload your trained model file (.pkl, .joblib, .h5, etc.)', upload_to='contributions/models/%Y/%m/')),
                ('scaler_file', models.FileField(blank=True, help_text='Upload scaler/preprocessor file if applicable', null=True, upload_to='contributions/scalers/%Y/%m/')),
                ('dataset_file', models.FileField(blank=True, help_text='Upload sample dataset (CSV, Excel, etc.)', null=True, upload_to='contributions/datasets/%Y/%m/')),
                ('code_file', models.FileField(blank=True, help_text='Upload your Python code file (.py or .ipynb)', null=True, upload_to='contributions/code/%Y/%m/')),
                ('dataset_sample', models.JSONField(blank=True, help_text='Sample data rows (will be auto-extracted from dataset_file or paste JSON)', null=True)),
                ('features_description', models.JSONField(blank=True, help_text='Description of input features as JSON object', null=True)),
                ('code_snippet', models.TextField(blank=True, help_text='Python code for model training/prediction')),
                ('selected_model', models.CharField(blank=True, help_text='Model algorithm used (e.g., Random Forest, XGBoost, Neural Network)', max_length=100)),
                ('accuracy_scores', models.JSONField(blank=True, help_text='Model performance metrics as JSON', null=True)),
                ('problem_statement_detail', models.TextField(blank=True, help_text='Detailed problem explanation for beginners')),
                ('approach_explanation', models.TextField(blank=True, help_text='Your approach and model selection reasoning')),
                ('preprocessing_steps', models.TextField(blank=True, help_text='Data preprocessing and feature engineering techniques')),
                ('model_architecture', models.TextField(blank=True, help_text='Model architecture, parameters, and hyperparameters')),
                ('model_info', models.TextField(blank=True, help_text='Additional model information')),
                ('requirements', models.TextField(blank=True, help_text='Python packages required (one per line)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Contribution',
                'verbose_name_plural': 'Model Contributions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
