# Generated by Django 5.2.7 on 2025-10-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dataset_sample', models.JSONField(help_text='Sample data rows for display')),
                ('model_type', models.CharField(default='Regression', max_length=100)),
                ('model_file', models.CharField(help_text='Path to the main model file', max_length=200)),
                ('scaler_file', models.CharField(blank=True, help_text='Path to the scaler file', max_length=200, null=True)),
                ('features_description', models.JSONField(help_text='Description of input features')),
                ('accuracy_scores', models.JSONField(help_text='Accuracy scores for different models')),
                ('selected_model', models.CharField(help_text='The model currently being used', max_length=100)),
                ('code_snippet', models.TextField(help_text='Python code for the model')),
                ('model_info', models.TextField(blank=True, help_text='Detailed information about the model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Problem Statement',
                'verbose_name_plural': 'Problem Statements',
            },
        ),
    ]
